/*
 * This source file was generated by the Gradle 'init' task
 */
package exerciseweek5;

import exerciseweek5.exercise5_1.Circle;
import exerciseweek5.exercise5_1.Rectangle;
import exerciseweek5.exercise5_1.Triangle;
import exerciseweek5.exercise5_2.Dog;
import exerciseweek5.exercise5_4.Bank;
import exerciseweek5.exercise5_4.CurrentAccount;
import exerciseweek5.exercise5_4.SavingsAccount;
import exerciseweek5.exercise5_5.Rectangle2;


public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());


/* ex5_1 */
    Rectangle rect = new Rectangle(3,5);
    // Create a Circle object with radius=3
    Circle circle = new Circle(3);
    // Create a Triangle object with base=4 and height=6
    Triangle triangle = new Triangle(4, 6);

    System.out.println(rect.getArea());
    System.out.println("Area of the Circle: " + circle.getArea());
    System.out.println("Area of the Triangle: " + triangle.getArea());

/* ex5_2 */
    Dog dogInstance = new Dog();
    dogInstance.bark();

/* ex5_4 */
    // Create an instance of the Bank class
    Bank bank = new Bank();
        
    // Create a SavingsAccount with an initial deposit and interest rate
    SavingsAccount savingsAccount = new SavingsAccount(1000.0, 1.25);
    System.out.println("\nSavings Account:\nInitial Deposit: $1000.00\nInterest rate: 1.25%");
        
    // Create a CurrentAccount with an initial deposit and overdraft limit
    CurrentAccount currentAccount = new CurrentAccount(5000.0, 1000.0);
    System.out.println("\nCurrent Account:\nInitial Deposit: $5000.00\nOverdraft Limit: $1000.00");
		
    // Add the SavingsAccount and CurrentAccount to the bank
	bank.addAccount(savingsAccount);
    bank.addAccount(currentAccount);
		
	System.out.println("\nNow deposit $100 to Savings Account.");
    // Deposit $100 into the SavingsAccount
    bank.deposit(savingsAccount, 100.0);
    System.out.println("Now deposit $500 to Current Account.");
	// Deposit $500 into the CurrentAccount
	bank.deposit(currentAccount, 500.0);
		
	System.out.println("Withdraw $150 from Savings Account.\n");
    // Withdraw $150 from the SavingsAccount
    bank.withdraw(savingsAccount, 150.0);
    System.out.println("\nSavings A/c and Current A/c.:");
		
    // Print the balances of all accounts in the bank
	bank.printAccountBalances();
		
    // Apply interest to the SavingsAccount
    savingsAccount.calculateInterest();
    System.out.println("\nAfter applying interest on Savings A/c for 1 year:");
	System.out.println("Savings A/c and Current A/c.:");
		
    // Print the balances of all accounts in the bank after applying interest
    bank.printAccountBalances();
    
/* ex5_5 */
    Rectangle2 rectangle2 = new Rectangle2(100,150);
    rectangle2.printSize();

    }  
}
