/*
 * This source file was generated by the Gradle 'init' task
 */
package javalecturepractice;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {

        //System.out.println(new App().getGreeting());
        week1 x = new week1();
        //x.ex1();
        //x.ex2();
        //x.ex3();
        //x.ex4();
        //x.ex5();
        x.ex6();

        
    }
}
